const env = process.env;

const Constants = {
  BASE_URL: env.REACT_APP_BASE_URL,
  AUTH_URL: env.REACT_APP_AUTH_URL,
  AUTH_REALM: env.REACT_APP_AUTH_REALM,
  AUTH_CLIENT_ID: env.REACT_APP_AUTH_CLIENT_ID,
  LIMIT_PER_FETCH: env.REACT_APP_LIMIT_PER_FETCH,
  REACT_APP_AWS_S3_BASE_URL: env.REACT_APP_AWS_S3_BASE_URL,
  HOME_TYPE: ['CONDO', 'HDB', 'BUILDING', 'APARTMENT', 'HOUSE', 'TRAILER'],
  PROPERTY_TYPE: ['SELL', 'RENT'],
  ROLE_NAME: ['CUSTOMER', 'OWNER', 'ADMIN'],
  OWNER_ROLE: 'OWNER',
  ADMIN_ROLE: 'ADMIN',
  CUSTOMER_ROLE: 'CUSTOMER',
  AUTH_TOKEN: env.REACT_APP_AUTH_TOKEN
};

export default Constants;